### ISSUE TITLE
Coredump when testing DeltaMerge

### ISSUE THREAD

**Issue by JinheLin** [pingcap/tiflash#2346]
I have met a coredump when I testing `DeltaMerge` with multithread read and write —— write operation is 128 rows per block and read operation is simply scanning the whole table.

```
#0  0x00007f8a49a5dd00 in pthread_mutex_lock () from /lib64/libpthread.so.0
#1  0x0000000002de7b41 in __gthread_mutex_lock (__mutex=0x5a5a5a5a5a5a5a72) at /usr/local/include/c++/7.3.0/x86_64-pc-linux-gnu/bits/gthr-default.h:748
#2  0x0000000002de7b91 in __gthread_recursive_mutex_lock (__mutex=0x5a5a5a5a5a5a5a72) at /usr/local/include/c++/7.3.0/x86_64-pc-linux-gnu/bits/gthr-default.h:810
#3  0x0000000002df5914 in std::recursive_mutex::lock (this=0x5a5a5a5a5a5a5a72) at /usr/local/include/c++/7.3.0/mutex:107
#4  0x0000000002e0d6b9 in std::unique_lock<std::recursive_mutex>::lock (this=0x7f8a3a243fe0) at /usr/local/include/c++/7.3.0/bits/std_mutex.h:267
#5  0x0000000002e04d9a in std::unique_lock<std::recursive_mutex>::unique_lock (this=0x7f8a3a243fe0, __m=...) at /usr/local/include/c++/7.3.0/bits/std_mutex.h:197
#6  0x0000000002de8131 in DB::Context::getLock (this=0x7f8a450ea000) at /data2/jinhelin/tics/dbms/src/Interpreters/Context.cpp:324
#7  0x0000000002deefa5 in DB::Context::getDeltaIndexManager (this=0x7f8a450ea000) at /data2/jinhelin/tics/dbms/src/Interpreters/Context.cpp:1445
#8  0x0000000003118e3a in DB::DM::DeltaValueSpace::abandon (this=0x7f89cf031510, context=...) at /data2/jinhelin/tics/dbms/src/Storages/DeltaMerge/Delta/DeltaValueSpace.cpp:86
#9  0x0000000002fd15d0 in DB::DM::Segment::abandon (this=0x7f8986c09250, context=...) at /data2/jinhelin/tics/dbms/src/Storages/DeltaMerge/Segment.h:234
#10 0x0000000002fc1afd in DB::DM::DeltaMergeStore::segmentMergeDelta (this=0x7f8a45161010, dm_context=..., segment=..., run_thread=DB::DM::DeltaMergeStore::Thread_BG_Thread_Pool) at /data2/jinhelin/tics/dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp:1876
#11 0x0000000002fbc972 in DB::DM::DeltaMergeStore::handleBackgroundTask (this=0x7f8a45161010, heavy=true) at /data2/jinhelin/tics/dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp:1365
#12 0x0000000002fb4ed0 in DB::DM::DeltaMergeStore::<lambda()>::operator()(void) const (__closure=0x7f8a450ab498) at /data2/jinhelin/tics/dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp:287
#13 0x0000000002fc65fa in std::_Function_handler<bool(), DB::DM::DeltaMergeStore::setUpBackgroundTask(const DMContextPtr&)::<lambda()> >::_M_invoke(const std::_Any_data &) (__functor=...) at /usr/local/include/c++/7.3.0/bits/std_function.h:302
#14 0x0000000003134c04 in std::function<bool ()>::operator()() const (this=0x7f8a450ab498) at /usr/local/include/c++/7.3.0/bits/std_function.h:706
#15 0x0000000003131410 in DB::BackgroundProcessingPool::threadFunction (this=0x7f8a4508c410) at /data2/jinhelin/tics/dbms/src/Storages/MergeTree/BackgroundProcessingPool.cpp:200
#16 0x0000000003130771 in DB::BackgroundProcessingPool::<lambda()>::operator()(void) const (__closure=0x7f8a45633518) at /data2/jinhelin/tics/dbms/src/Storages/MergeTree/BackgroundProcessingPool.cpp:65
#17 0x0000000003131a7a in std::__invoke_impl<void, DB::BackgroundProcessingPool::BackgroundProcessingPool(int)::<lambda()> >(std::__invoke_other, DB::BackgroundProcessingPool::<lambda()> &&) (__f=...) at /usr/local/include/c++/7.3.0/bits/invoke.h:60
#18 0x00000000031318b2 in std::__invoke<DB::BackgroundProcessingPool::BackgroundProcessingPool(int)::<lambda()> >(DB::BackgroundProcessingPool::<lambda()> &&) (__fn=...) at /usr/local/include/c++/7.3.0/bits/invoke.h:95
#19 0x000000000313401c in std::thread::_Invoker<std::tuple<DB::BackgroundProcessingPool::BackgroundProcessingPool(int)::<lambda()> > >::_M_invoke<0>(std::_Index_tuple<0>) (this=0x7f8a45633518) at /usr/local/include/c++/7.3.0/thread:234
#20 0x0000000003133fed in std::thread::_Invoker<std::tuple<DB::BackgroundProcessingPool::BackgroundProcessingPool(int)::<lambda()> > >::operator()(void) (this=0x7f8a45633518) at /usr/local/include/c++/7.3.0/thread:243
#21 0x0000000003133fcc in std::thread::_State_impl<std::thread::_Invoker<std::tuple<DB::BackgroundProcessingPool::BackgroundProcessingPool(int)::<lambda()> > > >::_M_run(void) (this=0x7f8a45633510) at /usr/local/include/c++/7.3.0/thread:186
#22 0x00000000053598cf in std::execute_native_thread_routine (__p=0x7f8a45633510) at ../../../.././libstdc++-v3/src/c++11/thread.cc:83
#23 0x00007f8a49a5bea5 in start_thread () from /lib64/libpthread.so.0
#24 0x00007f8a494829fd in clone () from /lib64/libc.so.6
```

**Comment by flowbehappy** [comment]
Closing it as cannot be reproduced.
