### ISSUE TITLE
TiFlash raise the error of region is unavailable 

### ISSUE THREAD

**Issue by lilinghai** [pingcap/tiflash#5532]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```
mysql> select count(*) from t;
ERROR 1105 (HY000): other error for mpp stream: Code: 0, e.displayText() = DB::TiFlashException: Region 5380 is unavailable: (while doing learner read for table, logical table_id: 68), e.what() = DB::TiFlashException,
```
the uptime of tiflash metirc(tiflash_system_asynchronous_metric_Uptime) keep unchanged
![image](https://user-images.githubusercontent.com/7677963/182751766-4d71e4cb-56a8-4ade-a811-9da5a83cde16.png)

**Comment by CalvinNeo** [comment]
<img width="871" alt="image" src="https://user-images.githubusercontent.com/5670241/182758357-caf6133f-e5be-4fcb-8730-5221a40999ca.png">

Thread 32 is blocked by Thread 31, with a lock

<img width="1419" alt="image" src="https://user-images.githubusercontent.com/5670241/182758325-d0f4a9fe-0001-4aff-987d-0f74e9980667.png">

<img width="1373" alt="image" src="https://user-images.githubusercontent.com/5670241/182758281-27e35207-58e8-4f9d-b0e0-0cd798a48b19.png">

**Comment by breezewish** [comment]
In tiflash-2, one apply-thread (apply-2, PID=59317) is stuck due to `flushCache` cannot be finished:

```
#0  0x0000ffff83d0fcb4 in nanosleep () from /lib64/libpthread.so.0
#1  0x0000ffff8714a79c in std::__1::this_thread::sleep_for(std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > const&) ()
   from /tiflash/libc++.so.1
#2  0x00000000063b14e0 in sleep_for<long long, std::__1::ratio<1, 1000> > (__d=...) at /usr/local/bin/../include/c++/v1/thread:379
#3  DB::DM::DeltaMergeStore::flushCache(std::__1::shared_ptr<DB::DM::DMContext> const&, DB::DM::RowKeyRange const&, bool) (this=<optimized out>, dm_context=...,
    range=..., try_until_succeed=<optimized out>)
    at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tics/dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp:1016
#4  0x0000000001be1a54 in DB::DM::DeltaMergeStore::flushCache(DB::Context const&, DB::DM::RowKeyRange const&, bool) (this=0xfff4a0380020, context=..., range=...,
    try_until_succeed=true) at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tics/dbms/src/Storages/DeltaMerge/DeltaMergeStore.h:380
#5  0x00000000065179cc in flushCache (this=<optimized out>, context=..., range_to_flush=..., try_until_succeed=true)
    at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tics/dbms/src/Storages/StorageDeltaMerge.cpp:786
#6  DB::KVStore::tryFlushRegionCacheInStorage(DB::TMTContext&, DB::Region const&, Poco::Logger*, bool) (tmt=..., region=..., log=<optimized out>,
    try_until_succeed=true) at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tics/dbms/src/Storages/Transaction/KVStore.cpp:154
#7  0x000000000651be3c in operator() (region=..., this=<optimized out>)
    at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tics/dbms/src/Storages/Transaction/KVStore.cpp:495
#8  operator() (this=<optimized out>) at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tics/dbms/src/Storages/Transaction/KVStore.cpp:555
#9  DB::KVStore::handleAdminRaftCmd(raft_cmdpb::AdminRequest&&, raft_cmdpb::AdminResponse&&, unsigned long, unsigned long, unsigned long, DB::TMTContext&) (
    this=0xffff40a11518, request=<optimized out>, response=<unknown type in /tiflash/tiflash, CU 0x663a60b, DIE 0x6675c96>, curr_region_id=5608,
    index=281471764749576, term=<optimized out>, tmt=...)
    at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tics/dbms/src/Storages/Transaction/KVStore.cpp:605
#10 0x0000000006530f34 in HandleAdminRaftCmd (server=<optimized out>, req_buff=..., resp_buff=..., header=...)
    at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tics/dbms/src/Storages/Transaction/ProxyFFI.cpp:116
#11 0x0000ffff85bb36c4 in raftstore::engine_store_ffi::_$LT$impl$u20$raftstore..engine_store_ffi..interfaces..root..DB..EngineStoreServerHelper$GT$::handle_admin_raft_cmd::hb936771030da97bf () from /tiflash/libtiflash_proxy.so
#12 0x0000ffff85553e48 in raftstore::store::fsm::apply::ApplyDelegate$LT$EK$GT$::exec_admin_cmd::h5d39fa7f2069e2cf () from /tiflash/libtiflash_proxy.so
#13 0x0000ffff85546f34 in raftstore::store::fsm::apply::ApplyDelegate$LT$EK$GT$::process_raft_cmd::ha0396bd1778fd5cd () from /tiflash/libtiflash_proxy.so
#14 0x0000ffff85545c50 in raftstore::store::fsm::apply::ApplyDelegate$LT$EK$GT$::handle_raft_committed_entries::h0aac2d505272f3fb ()
   from /tiflash/libtiflash_proxy.so
#15 0x0000ffff85561034 in raftstore::store::fsm::apply::ApplyFsm$LT$EK$GT$::handle_apply::h74c0b72499b90339 () from /tiflash/libtiflash_proxy.so
#16 0x0000ffff855639f8 in raftstore::store::fsm::apply::ApplyFsm$LT$EK$GT$::handle_tasks::hc57505dc8bb700b6 () from /tiflash/libtiflash_proxy.so
#17 0x0000ffff85566324 in _$LT$raftstore..store..fsm..apply..ApplyPoller$LT$EK$GT$$u20$as$u20$batch_system..batch..PollHandler$LT$raftstore..store..fsm..apply..ApplyFsm$LT$EK$GT$$C$raftstore..store..fsm..apply..ControlFsm$GT$$GT$::handle_normal::ha4565cf6507a3216 () from /tiflash/libtiflash_proxy.so
#18 0x0000ffff85175338 in batch_system::batch::Poller$LT$N$C$C$C$Handler$GT$::poll::hc14ea824bead376d () from /tiflash/libtiflash_proxy.so
#19 0x0000ffff8584136c in std::sys_common::backtrace::__rust_begin_short_backtrace::h80953f8e29109df0 () from /tiflash/libtiflash_proxy.so
#20 0x0000ffff85066908 in core::ops::function::FnOnce::call_once$u7b$$u7b$vtable.shim$u7d$$u7d$::h8b14e8f2aab21868 () from /tiflash/libtiflash_proxy.so
#21 0x0000ffff85eff01c in std::sys::unix::thread::Thread::new::thread_start::h4e461bcfb14a5bff () from /tiflash/libtiflash_proxy.so
#22 0x0000ffff83d07d38 in start_thread () from /lib64/libpthread.so.0
#23 0x0000ffff83c0f690 in thread_start () from /lib64/libc.so.6
```

```
[pid 59317] nanosleep({tv_sec=0, tv_nsec=100000000},  <unfinished ...>
[pid 57780] nanosleep({tv_sec=0, tv_nsec=100000000},  <unfinished ...>
[pid 59317] nanosleep({tv_sec=0, tv_nsec=100000000},  <unfinished ...>
[pid 57780] nanosleep({tv_sec=0, tv_nsec=100000000},  <unfinished ...>
[pid 59317] nanosleep({tv_sec=0, tv_nsec=100000000},  <unfinished ...>
[pid 57780] nanosleep({tv_sec=0, tv_nsec=100000000},  <unfinished ...>
[pid 59317] nanosleep({tv_sec=0, tv_nsec=100000000},  <unfinished ...>
[pid 57780] nanosleep({tv_sec=0, tv_nsec=100000000},  <unfinished ...>
```

**Comment by CalvinNeo** [comment]
It is found that there is a deaadlock here
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/5670241/182782146-e13a28ae-9126-47e0-92d7-93f1f83eb9a9.png">

**Comment by breezewish** [comment]
3 related threads:

```
Thread 895 (Thread 0xfffdaaa3b2f0 (LWP 61)):
#0  0x0000ffff83d0f008 in __lll_lock_wait () from /lib64/libpthread.so.0
#1  0x0000ffff83d09c40 in pthread_mutex_lock () from /lib64/libpthread.so.0
#2  0x0000ffff87140b38 in std::__1::mutex::lock() () from /tiflash/libc++.so.1
#3  0x000000000663e72c in lock_guard (__m=..., this=<optimized out>) at /usr/local/bin/../include/c++/v1/__mutex_base:90
#4  lock (this=<optimized out>) at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tics/dbms/src/Storages/Page/V3/BlobStore.cpp:1279
#5  operator() (this=<optimized out>) at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tics/dbms/src/Storages/Page/V3/BlobStore.cpp:445
#6  DB::PS::V3::BlobStore::getPosFromStats(unsigned long) (this=0xffff4079a0f0, size=<optimized out>)
    at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tics/dbms/src/Storages/Page/V3/BlobStore.cpp:444
#7  0x0000000006640fcc in DB::PS::V3::BlobStore::write(DB::WriteBatch&, std::__1::shared_ptr<DB::WriteLimiter> const&) (this=0xffff4079a0f0, wb=...,
    write_limiter=...) at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tics/dbms/src/Storages/Page/V3/BlobStore.cpp:294
#8  0x0000000006655848 in DB::PS::V3::PageStorageImpl::writeImpl(DB::WriteBatch&&, std::__1::shared_ptr<DB::WriteLimiter> const&) (this=0xffff40799f18,
    write_batch=<unknown type in /tiflash/tiflash, CU 0x70a4862, DIE 0x70d7f68>, write_limiter=...)
    at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tics/dbms/src/Storages/Page/V3/PageStorageImpl.cpp:109
#9  0x0000000006688200 in write (this=0xffff4079a1e0, write_batch=<unknown type in /tiflash/tiflash, CU 0x726b677, DIE 0x728c75d>, write_limiter=...)
    at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tics/dbms/src/Storages/Page/PageStorage.h:276
#10 writeIntoV3 (this=<optimized out>, write_batch=<unknown type in /tiflash/tiflash, CU 0x726b677, DIE 0x728c70c>, write_limiter=...)
    at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tics/dbms/src/Storages/Page/PageStorage.cpp:484
#11 DB::PageWriter::write(DB::WriteBatch&&, std::__1::shared_ptr<DB::WriteLimiter>) const (this=0xfff4a0160358,
    write_batch=<unknown type in /tiflash/tiflash, CU 0x726b677, DIE 0x728c518>, write_limiter=...)
    at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tics/dbms/src/Storages/Page/PageStorage.cpp:466
#12 0x00000000063b0b94 in DB::DM::WriteBatches::writeLogAndData() (this=0xfffdaaa39bd8)
    at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tics/dbms/src/Storages/DeltaMerge/WriteBatches.h:115
#13 0x00000000064c2bb4 in DB::DM::ColumnFileFlushTask::prepare(DB::DM::WriteBatches&) (this=0xffebe00c5658, wbs=...)
    at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tics/dbms/src/Storages/DeltaMerge/Delta/ColumnFileFlushTask.cpp:58
#14 0x00000000064b4160 in DB::DM::DeltaValueSpace::flush(DB::DM::DMContext&) (this=0xffebe1324a78, context=...)
    at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tics/dbms/src/Storages/DeltaMerge/Delta/DeltaValueSpace.cpp:186
#15 0x00000000063e28a4 in DB::DM::Segment::flushCache(DB::DM::DMContext&) (this=0xffebe1320018, dm_context=...)
    at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tics/dbms/src/Storages/DeltaMerge/Segment.cpp:1357
#16 0x00000000063a9fe8 in DB::DM::DeltaMergeStore::checkSegmentUpdate(std::__1::shared_ptr<DB::DM::DMContext> const&, std::__1::shared_ptr<DB::DM::Segment> const&, DB::DM::DeltaMergeStore::ThreadType) (this=0xfff4a0380020, dm_context=..., segment=..., thread_type=<optimized out>)
    at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tics/dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp:1498
#17 0x00000000063bc6f0 in DB::DM::DeltaMergeStore::handleBackgroundTask(bool) (this=<optimized out>, heavy=<optimized out>)
    at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tics/dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp:1754
#18 0x000000000630e148 in operator() (this=0xfff4a01f03f0) at /usr/local/bin/../include/c++/v1/__functional/function.h:498
#19 operator() (this=0xfff4a01f03f0) at /usr/local/bin/../include/c++/v1/__functional/function.h:1175
#20 threadFunction (this=0xffff408808d8)
    at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tics/dbms/src/Storages/BackgroundProcessingPool.cpp:230
#21 operator() (this=<optimized out>) at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tics/dbms/src/Storages/BackgroundProcessingPool.cpp:93
#22 __invoke<(lambda at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tics/dbms/src/Storages/BackgroundProcessingPool.cpp:93:30)> (
    __f=<optimized out>) at /usr/local/bin/../include/c++/v1/type_traits:3918
#23 __thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, (lambda at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tics/dbms/src/Storages/BackgroundProcessingPool.cpp:93:30)> (__t=...) at /usr/local/bin/../include/c++/v1/thread:280
#24 std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, DB::BackgroundProcessingPool::BackgroundProcessingPool(int)::$_2> >(void*) (__vp=0xffff400504d0) at /usr/local/bin/../include/c++/v1/thread:291
#25 0x0000ffff83d07d38 in start_thread () from /lib64/libpthread.so.0
#26 0x0000ffff83c0f690 in thread_start () from /lib64/libc.so.6



Thread 23 (Thread 0xffd1c00cb2f0 (LWP 1029)):
#0  0x0000ffff83d0fcb4 in nanosleep () from /lib64/libpthread.so.0
#1  0x0000ffff8714a79c in std::__1::this_thread::sleep_for(std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > const&) ()
   from /tiflash/libc++.so.1
#2  0x00000000063b14e0 in sleep_for<long long, std::__1::ratio<1, 1000> > (__d=...) at /usr/local/bin/../include/c++/v1/thread:379
#3  DB::DM::DeltaMergeStore::flushCache(std::__1::shared_ptr<DB::DM::DMContext> const&, DB::DM::RowKeyRange const&, bool) (this=<optimized out>, dm_context=...,
    range=..., try_until_succeed=<optimized out>)
    at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tics/dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp:1016
#4  0x0000000001be1a54 in DB::DM::DeltaMergeStore::flushCache(DB::Context const&, DB::DM::RowKeyRange const&, bool) (this=0xfff4a0380020, context=..., range=...,
    try_until_succeed=true) at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tics/dbms/src/Storages/DeltaMerge/DeltaMergeStore.h:380
#5  0x00000000065179cc in flushCache (this=<optimized out>, context=..., range_to_flush=..., try_until_succeed=true)
    at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tics/dbms/src/Storages/StorageDeltaMerge.cpp:786
#6  DB::KVStore::tryFlushRegionCacheInStorage(DB::TMTContext&, DB::Region const&, Poco::Logger*, bool) (tmt=..., region=..., log=<optimized out>,
    try_until_succeed=true) at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tics/dbms/src/Storages/Transaction/KVStore.cpp:154
#7  0x000000000651be3c in operator() (region=..., this=<optimized out>)
    at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tics/dbms/src/Storages/Transaction/KVStore.cpp:495
#8  operator() (this=<optimized out>) at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tics/dbms/src/Storages/Transaction/KVStore.cpp:555
#9  DB::KVStore::handleAdminRaftCmd(raft_cmdpb::AdminRequest&&, raft_cmdpb::AdminResponse&&, unsigned long, unsigned long, unsigned long, DB::TMTContext&) (
    this=0xffff40a11518, request=<optimized out>, response=<unknown type in /tiflash/tiflash, CU 0x663a60b, DIE 0x6675c96>, curr_region_id=5608,
    index=281471764749576, term=<optimized out>, tmt=...)
    at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tics/dbms/src/Storages/Transaction/KVStore.cpp:605
#10 0x0000000006530f34 in HandleAdminRaftCmd (server=<optimized out>, req_buff=..., resp_buff=..., header=...)
    at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tics/dbms/src/Storages/Transaction/ProxyFFI.cpp:116
#11 0x0000ffff85bb36c4 in raftstore::engine_store_ffi::_$LT$impl$u20$raftstore..engine_store_ffi..interfaces..root..DB..EngineStoreServerHelper$GT$::handle_admin_raft_cmd::hb936771030da97bf () from /tiflash/libtiflash_proxy.so
#12 0x0000ffff85553e48 in raftstore::store::fsm::apply::ApplyDelegate$LT$EK$GT$::exec_admin_cmd::h5d39fa7f2069e2cf () from /tiflash/libtiflash_proxy.so
#13 0x0000ffff85546f34 in raftstore::store::fsm::apply::ApplyDelegate$LT$EK$GT$::process_raft_cmd::ha0396bd1778fd5cd () from /tiflash/libtiflash_proxy.so
#14 0x0000ffff85545c50 in raftstore::store::fsm::apply::ApplyDelegate$LT$EK$GT$::handle_raft_committed_entries::h0aac2d505272f3fb ()
   from /tiflash/libtiflash_proxy.so
#15 0x0000ffff85561034 in raftstore::store::fsm::apply::ApplyFsm$LT$EK$GT$::handle_apply::h74c0b72499b90339 () from /tiflash/libtiflash_proxy.so
#16 0x0000ffff855639f8 in raftstore::store::fsm::apply::ApplyFsm$LT$EK$GT$::handle_tasks::hc57505dc8bb700b6 () from /tiflash/libtiflash_proxy.so
#17 0x0000ffff85566324 in _$LT$raftstore..store..fsm..apply..ApplyPoller$LT$EK$GT$$u20$as$u20$batch_system..batch..PollHandler$LT$raftstore..store..fsm..apply..ApplyFsm$LT$EK$GT$$C$raftstore..store..fsm..apply..ControlFsm$GT$$GT$::handle_normal::ha4565cf6507a3216 () from /tiflash/libtiflash_proxy.so
#18 0x0000ffff85175338 in batch_system::batch::Poller$LT$N$C$C$C$Handler$GT$::poll::hc14ea824bead376d () from /tiflash/libtiflash_proxy.so
#19 0x0000ffff8584136c in std::sys_common::backtrace::__rust_begin_short_backtrace::h80953f8e29109df0 () from /tiflash/libtiflash_proxy.so
#20 0x0000ffff85066908 in core::ops::function::FnOnce::call_once$u7b$$u7b$vtable.shim$u7d$$u7d$::h8b14e8f2aab21868 () from /tiflash/libtiflash_proxy.so
#21 0x0000ffff85eff01c in std::sys::unix::thread::Thread::new::thread_start::h4e461bcfb14a5bff () from /tiflash/libtiflash_proxy.so
#22 0x0000ffff83d07d38 in start_thread () from /lib64/libpthread.so.0
#23 0x0000ffff83c0f690 in thread_start () from /lib64/libc.so.6




Thread 22 (Thread 0xffd1bfebb2f0 (LWP 1030)):
#0  0x0000ffff83d0f008 in __lll_lock_wait () from /lib64/libpthread.so.0
#1  0x0000ffff83d09c40 in pthread_mutex_lock () from /lib64/libpthread.so.0
#2  0x0000ffff87140b38 in std::__1::mutex::lock() () from /tiflash/libc++.so.1
#3  0x000000000663e72c in lock_guard (__m=..., this=<optimized out>) at /usr/local/bin/../include/c++/v1/__mutex_base:90
#4  lock (this=<optimized out>) at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tics/dbms/src/Storages/Page/V3/BlobStore.cpp:1279
#5  operator() (this=<optimized out>) at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tics/dbms/src/Storages/Page/V3/BlobStore.cpp:445
#6  DB::PS::V3::BlobStore::getPosFromStats(unsigned long) (this=0xffff4079a0f0, size=<optimized out>)
    at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tics/dbms/src/Storages/Page/V3/BlobStore.cpp:444
#7  0x0000000006640fcc in DB::PS::V3::BlobStore::write(DB::WriteBatch&, std::__1::shared_ptr<DB::WriteLimiter> const&) (this=0xffff4079a0f0, wb=...,
    write_limiter=...) at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tics/dbms/src/Storages/Page/V3/BlobStore.cpp:294
#8  0x0000000006655848 in DB::PS::V3::PageStorageImpl::writeImpl(DB::WriteBatch&&, std::__1::shared_ptr<DB::WriteLimiter> const&) (this=0xffff40799f18,
    write_batch=<unknown type in /tiflash/tiflash, CU 0x70a4862, DIE 0x70d7f68>, write_limiter=...)
    at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tics/dbms/src/Storages/Page/V3/PageStorageImpl.cpp:109
#9  0x0000000006688200 in write (this=0xffff4079a1e0, write_batch=<unknown type in /tiflash/tiflash, CU 0x726b677, DIE 0x728c75d>, write_limiter=...)
    at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tics/dbms/src/Storages/Page/PageStorage.h:276
#10 writeIntoV3 (this=<optimized out>, write_batch=<unknown type in /tiflash/tiflash, CU 0x726b677, DIE 0x728c70c>, write_limiter=...)
    at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tics/dbms/src/Storages/Page/PageStorage.cpp:484
#11 DB::PageWriter::write(DB::WriteBatch&&, std::__1::shared_ptr<DB::WriteLimiter>) const (this=0xfff4a0160358,
    write_batch=<unknown type in /tiflash/tiflash, CU 0x726b677, DIE 0x728c518>, write_limiter=...)
    at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tics/dbms/src/Storages/Page/PageStorage.cpp:466
#12 0x00000000063b0b94 in DB::DM::WriteBatches::writeLogAndData() (this=0xffd1bfeb5b68)
    at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tics/dbms/src/Storages/DeltaMerge/WriteBatches.h:115
#13 0x00000000064c2bb4 in DB::DM::ColumnFileFlushTask::prepare(DB::DM::WriteBatches&) (this=0xfff1e00e7618, wbs=...)
    at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tics/dbms/src/Storages/DeltaMerge/Delta/ColumnFileFlushTask.cpp:58
#14 0x00000000064b4160 in DB::DM::DeltaValueSpace::flush(DB::DM::DMContext&) (this=0xffebe1321dd8, context=...)
    at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tics/dbms/src/Storages/DeltaMerge/Delta/DeltaValueSpace.cpp:186
#15 0x00000000063e28a4 in DB::DM::Segment::flushCache(DB::DM::DMContext&) (this=0xffebe1323e38, dm_context=...)
    at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tics/dbms/src/Storages/DeltaMerge/Segment.cpp:1357
#16 0x00000000063a9fe8 in DB::DM::DeltaMergeStore::checkSegmentUpdate(std::__1::shared_ptr<DB::DM::DMContext> const&, std::__1::shared_ptr<DB::DM::Segment> const&, DB::DM::DeltaMergeStore::ThreadType) (this=0xfff4a0380020, dm_context=..., segment=..., thread_type=<optimized out>)
    at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tics/dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp:1498
#17 0x00000000063af3d4 in DB::DM::DeltaMergeStore::write(DB::Context const&, DB::Settings const&, DB::Block&) (this=0xfff4a0380020, db_context=..., db_settings=...,
    block=...) at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tics/dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp:700
#18 0x000000000652f11c in write (this=0xffe4a0720018, block=..., settings=...)
    at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tics/dbms/src/Storages/StorageDeltaMerge.cpp:527
#19 DB::writeRegionDataToStorage(DB::Context&, DB::RegionPtrWithBlock const&, std::__1::vector<std::__1::tuple<DB::RawTiDBPK, unsigned char, unsigned long, std::__1::shared_ptr<DB::StringObject<false> const> >, std::__1::allocator<std::__1::tuple<DB::RawTiDBPK, unsigned char, unsigned long, std::__1::shared_ptr<DB::StringObject<false> const> > > >&, Poco::Logger*)::$_0::operator()(bool) const (this=0xffd1bfeb6dd0, force_decode=<optimized out>)
    at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tics/dbms/src/Storages/Transaction/PartitionStreams.cpp:148
#20 0x000000000652b314 in DB::writeRegionDataToStorage(DB::Context&, DB::RegionPtrWithBlock const&, std::__1::vector<std::__1::tuple<DB::RawTiDBPK, unsigned char, unsigned long, std::__1::shared_ptr<DB::StringObject<false> const> >, std::__1::allocator<std::__1::tuple<DB::RawTiDBPK, unsigned char, unsigned long, std::__1::shared_ptr<DB::StringObject<false> const> > > >&, Poco::Logger*) (context=..., region=..., data_list_read=..., log=<optimized out>)
    at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tics/dbms/src/Storages/Transaction/PartitionStreams.cpp:181
#21 0x000000000652acc4 in DB::RegionTable::writeBlockByRegion(DB::Context&, DB::RegionPtrWithBlock const&, std::__1::vector<std::__1::tuple<DB::RawTiDBPK, unsigned char, unsigned long, std::__1::shared_ptr<DB::StringObject<false> const> >, std::__1::allocator<std::__1::tuple<DB::RawTiDBPK, unsigned char, unsigned long, std::__1::shared_ptr<DB::StringObject<false> const> > > >&, Poco::Logger*, bool) (context=..., region=..., data_list_to_remove=..., log=0xfff4a0160000, lock_region=false)
    at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tics/dbms/src/Storages/Transaction/PartitionStreams.cpp:364
#22 0x00000000065473d4 in DB::Region::handleWriteRaftCmd(DB::WriteCmdsView const&, unsigned long, unsigned long, DB::TMTContext&) (this=0xfff4a0330018, cmds=...,
    index=<optimized out>, term=<optimized out>, tmt=...)
    at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tics/dbms/src/Storages/Transaction/Region.cpp:712
#23 0x0000000006519538 in DB::KVStore::handleWriteRaftCmd(DB::WriteCmdsView const&, unsigned long, unsigned long, unsigned long, DB::TMTContext&) (
    this=0xffff40a11518, cmds=..., region_id=147, index=8709463, term=6, tmt=...)
    at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tics/dbms/src/Storages/Transaction/KVStore.cpp:287
#24 0x0000000006530de0 in HandleWriteRaftCmd (server=<optimized out>, cmds=<error reading variable: Cannot access memory at address 0x80>, header=...)
    at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tics/dbms/src/Storages/Transaction/ProxyFFI.cpp:94
#25 0x0000ffff855480fc in raftstore::store::fsm::apply::ApplyDelegate$LT$EK$GT$::process_raft_cmd::ha0396bd1778fd5cd () from /tiflash/libtiflash_proxy.so
#26 0x0000ffff85545f34 in raftstore::store::fsm::apply::ApplyDelegate$LT$EK$GT$::handle_raft_committed_entries::h0aac2d505272f3fb ()
   from /tiflash/libtiflash_proxy.so
#27 0x0000ffff85561034 in raftstore::store::fsm::apply::ApplyFsm$LT$EK$GT$::handle_apply::h74c0b72499b90339 () from /tiflash/libtiflash_proxy.so
#28 0x0000ffff855639f8 in raftstore::store::fsm::apply::ApplyFsm$LT$EK$GT$::handle_tasks::hc57505dc8bb700b6 () from /tiflash/libtiflash_proxy.so
#29 0x0000ffff85566324 in _$LT$raftstore..store..fsm..apply..ApplyPoller$LT$EK$GT$$u20$as$u20$batch_system..batch..PollHandler$LT$raftstore..store..fsm..apply..ApplyFsm$LT$EK$GT$$C$raftstore..store..fsm..apply..ControlFsm$GT$$GT$::handle_normal::ha4565cf6507a3216 () from /tiflash/libtiflash_proxy.so
#30 0x0000ffff85175338 in batch_system::batch::Poller$LT$N$C$C$C$Handler$GT$::poll::hc14ea824bead376d () from /tiflash/libtiflash_proxy.so
#31 0x0000ffff8584136c in std::sys_common::backtrace::__rust_begin_short_backtrace::h80953f8e29109df0 () from /tiflash/libtiflash_proxy.so
#32 0x0000ffff85066908 in core::ops::function::FnOnce::call_once$u7b$$u7b$vtable.shim$u7d$$u7d$::h8b14e8f2aab21868 () from /tiflash/libtiflash_proxy.so
#33 0x0000ffff85eff01c in std::sys::unix::thread::Thread::new::thread_start::h4e461bcfb14a5bff () from /tiflash/libtiflash_proxy.so
#34 0x0000ffff83d07d38 in start_thread () from /lib64/libpthread.so.0
#35 0x0000ffff83c0f690 in thread_start () from /lib64/libc.so.6
```

**Comment by JaySon-Huang** [comment]
The root cause and fix:
* https://github.com/pingcap/tiflash/issues/5552
* https://github.com/pingcap/tiflash/pull/5550
