### ISSUE TITLE
When starting tiflash, crash appears

### ISSUE THREAD

**Issue by AntiTopQuark** [pingcap/tiflash#6682]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Compile tiflash according to README, then use tiup to start all components.
```sh
mkdir cmake-build-debug  # The directory name can be customized
cd cmake-build-debug
cmake .. -GNinja -DCMAKE_BUILD_TYPE=DEBUG 
ninja tiflash
tiup playground nightly --tiflash.binpath ./dbms/src/Server/tiflash
```

### 2. What did you expect to see? (Required)
tiflash starts normally
### 3. What did you see instead (Required)
output of tiup:
```
......
The component `prometheus` version v6.6.0-alpha-nightly-20230127 is not installed; downloading from repository.
download https://tiup-mirrors.pingcap.com/prometheus-v6.6.0-alpha-nightly-20230127-linux-amd64.tar.gz 92.26 MiB / 92.26 MiB 100.00% 9.68 MiB/s
download https://tiup-mirrors.pingcap.com/grafana-v6.6.0-alpha-nightly-20230127-linux-amd64.tar.gz 50.08 MiB / 50.08 MiB 100.00% 8.95 MiB/s
Start tiflash instance:v6.6.0-alpha-nightly-20230127
Waiting for tiflash instances ready
127.0.0.1:3930 ... ⠦
tiflash quit: signal: aborted (core dumped)
/usr/lib/llvm-13/bin/../include/c++/v1/vector:1571: _LIBCPP_ASSERT '__n < size()' failed. vector[] index out of bounds
/usr/lib/llvm-13/bin/../include/c++/v1/vector:1571: _LIBCPP_ASSERT '__n < size()' failed. vector[] index out of bounds
/usr/lib/llvm-13/bin/../include/c++/v1/vector:1571: _LIBCPP_ASSERT '__n < size()' failed. vector[] index out of bounds
/usr/lib/llvm-13/bin/../include/c++/v1/vector:1571: _LIBCPP_ASSERT '__n < size()' failed. vector[] index out of bounds
/usr/lib/llvm-13/bin/../include/c++/v1/vector:1571: _LIBCPP_ASSERT '__n < size()' failed. vector[] index out of bounds
/usr/lib/llvm-13/bin/../include/c++/v1/vector:1571: _LIBCPP_ASSERT '__n < size()' failed. vector[] index out of bounds
/usr/lib/llvm-13/bin/../include/c++/v1/vector:1571: _LIBCPP_ASSERT '__n < size()' failed. vector[] index out of bounds
/usr/lib/llvm-13/bin/../include/c++/v1/vector:1571: _LIBCPP_ASSERT '__n < size()' failed. vector[] index out of bounds
/usr/lib/llvm-13/bin/../include/c++/v1/vector:1571: _LIBCPP_ASSERT '__n < size()' failed. vector[] index out of bounds
/usr/lib/llvm-13/bin/../include/c++/v1/vector:1571: _LIBCPP_ASSERT '__n < size()' failed. vector[] index out of bounds
Waiting for tiflash instances ready
127.0.0.1:3930 ... Error
CLUSTER START SUCCESSFULLY, Enjoy it ^-^
To connect TiDB: mysql --comments --host 127.0.0.1 --port 4000 -u root -p (no password)
To view the dashboard: http://127.0.0.1:2379/dashboard
PD client endpoints: [127.0.0.1:2379]
To view the Prometheus: http://127.0.0.1:9090
To view the Grafana: http://127.0.0.1:3000
...
```

the back trace of gdb:
```
/usr/lib/llvm-13/bin/../include/c++/v1/vector:1571: _LIBCPP_ASSERT '__n < size()' failed. vector[] index out of bounds
/usr/lib/llvm-13/bin/../include/c++/v1/vector:1571: _LIBCPP_ASSERT '__n < size()' failed. vector[] index out of bounds
/usr/lib/llvm-13/bin/../include/c++/v1/vector:1571: _LIBCPP_ASSERT '__n < size()' failed. vector[] index out of bounds
/usr/lib/llvm-13/bin/../include/c++/v1/vector:1571: _LIBCPP_ASSERT '__n < size()' failed. vector[] index out of bounds
/usr/lib/llvm-13/bin/../include/c++/v1/vector:1571: _LIBCPP_ASSERT '__n < size()' failed. vector[] index out of bounds
/usr/lib/llvm-13/bin/../include/c++/v1/vector:1571: _LIBCPP_ASSERT '__n < size()' failed. vector[] index out of bounds
--Type <RET> for more, q to quit, c to continue without paging--

Thread 123 "FixedThread" received signal SIGABRT, Aborted.
Thread 123 "FixedThread" received signal SIGABRT, Aborted.
[Switching to Thread 0x7fff95031700 (LWP 8303)]
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007fffeee2d859 in __GI_abort () at abort.c:79
#2  0x00007ffff7f4082f in std::__1::__libcpp_abort_debug_function(std::__1::__libcpp_debug_info const&) () from /lib/x86_64-linux-gnu/libc++.so.1
#3  0x0000000000afaf6a in std::__1::vector<prometheus::Gauge*, std::__1::allocator<prometheus::Gauge*> >::operator[] (this=0xeb40a70 <DB::TiFlashMetrics::instance()::inst+1064>,
    __n=3) at /usr/lib/llvm-13/bin/../include/c++/v1/vector:1571
#4  0x0000000000add84d in DB::MetricFamily<prometheus::Gauge>::get (this=0xeb40a70 <DB::TiFlashMetrics::instance()::inst+1064>, idx=3)
    at /home/antitopquark/project/support_ipv4_and_ipv6_func/dbms/src/Common/TiFlashMetrics.h:365
#5  0x0000000009c05a05 in DB::DynamicThreadPool::fixedWork(unsigned long)::$_1::operator()() const (this=0x7fff95006ff8)
    at /home/antitopquark/project/support_ipv4_and_ipv6_func/dbms/src/Common/DynamicThreadPool.cpp:107
#6  0x0000000009c05895 in ext::ScopeGuard<DB::DynamicThreadPool::fixedWork(unsigned long)::$_1>::~ScopeGuard() (this=0x7fff95006ff8)
    at /home/antitopquark/project/support_ipv4_and_ipv6_func/libs/libcommon/include/ext/scope_guard.h:33
#7  0x0000000009c0512b in DB::DynamicThreadPool::fixedWork (this=0x7fffd0b5e700, index=30)
    at /home/antitopquark/project/support_ipv4_and_ipv6_func/dbms/src/Common/DynamicThreadPool.cpp:119
#8  0x0000000009c09184 in std::__1::__invoke<void (DB::DynamicThreadPool::* const&)(unsigned long), DB::DynamicThreadPool*, unsigned long&, void> (__f=
    @0x7fffb30de750: (void (DB::DynamicThreadPool::*)(class DB::DynamicThreadPool * const, unsigned long)) 0x9c04f70 <DB::DynamicThreadPool::fixedWork(unsigned long)>,
    __a0=@0x7fffb30de760: 0x7fffd0b5e700, __args=@0x7fffb30de768: 30) at /usr/lib/llvm-13/bin/../include/c++/v1/type_traits:3859
#9  0x0000000009c09097 in std::__1::invoke<void (DB::DynamicThreadPool::* const&)(unsigned long), DB::DynamicThreadPool*, unsigned long&> (__f=
    @0x7fffb30de750: (void (DB::DynamicThreadPool::*)(class DB::DynamicThreadPool * const, unsigned long)) 0x9c04f70 <DB::DynamicThreadPool::fixedWork(unsigned long)>,
    __args=@0x7fffb30de768: 30, __args=@0x7fffb30de768: 30) at /usr/lib/llvm-13/bin/../include/c++/v1/__functional/invoke.h:93
#10 0x0000000009c08fd9 in _ZZN2DB13ThreadFactory9newThreadIMNS_17DynamicThreadPoolEFvmEJPS2_RmEEENSt3__16threadEbNS7_12basic_stringIcNS7_11char_traitsIcEENS7_9allocatorIcEEEEOT_DpOT0_ENKUlDpOT_E_clIJS5_mEEEDaSM_ (this=0x7fffb30de728, args=@0x7fffb30de768: 30, args=@0x7fffb30de768: 30)
    at /home/antitopquark/project/support_ipv4_and_ipv6_func/dbms/src/Common/ThreadFactory.h:47
#11 0x0000000009c08dc5 in _ZNSt3__18__invokeIZN2DB13ThreadFactory9newThreadIMNS1_17DynamicThreadPoolEFvmEJPS4_RmEEENS_6threadEbNS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEEOT_DpOT0_EUlDpOT_E_JS7_mEEEDTclscSG_fp_spscSI_fp0_EESH_SK_ (__f=..., __args=@0x7fffb30de768: 30, __args=@0x7fffb30de768: 30)
    at /usr/lib/llvm-13/bin/../include/c++/v1/type_traits:3918
#12 0x0000000009c08d97 in _ZNSt3__116__thread_executeINS_10unique_ptrINS_15__thread_structENS_14default_deleteIS2_EEEEZN2DB13ThreadFactory9newThreadIMNS6_17DynamicThreadPoolEFvmEJPS9_RmEEENS_6threadEbNS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEEOT_DpOT0_EUlDpOT_E_JSC_mEJLm2ELm3EEEEvRNS_5tupleIJSL_T0_DpT1_EEENS_15__tuple_indicesIJXspT2_EEEE (
    __t=...) at /usr/lib/llvm-13/bin/../include/c++/v1/thread:280
#13 0x0000000009c089a2 in _ZNSt3__114__thread_proxyINS_5tupleIJNS_10unique_ptrINS_15__thread_structENS_14default_deleteIS3_EEEEZN2DB13ThreadFactory9newThreadIMNS7_17DynamicThreadPoolEFvmEJPSA_RmEEENS_6threadEbNS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEEOT_DpOT0_EUlDpOT_E_SD_mEEEEEPvSW_ (__vp=0x7fffb30de720)
    at /usr/lib/llvm-13/bin/../include/c++/v1/thread:291
#14 0x00007fffef0ec609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#15 0x00007fffeef2a133 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```
### 4. What is your TiFlash version? (Required)
master branch
commit hash is b88b2aa2221ec8de745908c94129154a6fdef965

### 5. Environment
- cmake version: 3.23.0
- clang version:  13.0.1-++20220120110924+75e33f71c2da-1~exp1~20220120231001.58
- rustup 1.25.1 (bb60b1e89 2022-07-12)
-  wsl verson:
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.4 LTS
Release:        20.04
Codename:       focal

**Comment by ywqzzy** [comment]
This is one known issue, you can build a release bin to skip it.
However, It is caused by when TiFlashMetric was destroyed, DynamicThreadPool still didn't destroyed.

**Comment by AntiTopQuark** [comment]
> didn't

Thank you very much, it worked.
