### ISSUE TITLE
Unit test `SimpleOperatorTestRunner.Projection` asan fail

### ISSUE THREAD

**Issue by SeaRise** [pingcap/tiflash#7955]
```
[2023-08-16T19:28:15.155Z] Received signal Segmentation fault
[2023-08-16T19:28:15.155Z] 
[2023-08-16T19:28:15.155Z]        0x48e95fb	__interceptor_backtrace [gtests_dbms+76453371]
[2023-08-16T19:28:15.155Z]                 	/llvm-project/compiler-rt/lib/asan/../sanitizer_common/sanitizer_common_interceptors.inc:4202
[2023-08-16T19:28:15.155Z]       0x1ff05923	StackTrace::StackTrace() [gtests_dbms+535845155]
[2023-08-16T19:28:15.155Z]                 	dbms/src/Common/StackTrace.cpp:23
[2023-08-16T19:28:15.155Z]        0xc91eb2d	fault_signal_handler(int) [gtests_dbms+210889517]
[2023-08-16T19:28:15.155Z]                 	dbms/src/TestUtils/gtests_dbms_main.cpp:40
[2023-08-16T19:28:15.155Z]   0x7ff8fd698400	<unknown symbol> [libc.so.6+222208]
[2023-08-16T19:28:15.155Z]       0x1cbbabaf	DB::TransformOp::tryOutput(DB::Block&) [gtests_dbms+482061231]
[2023-08-16T19:28:15.155Z]                 	dbms/src/Operators/Operator.cpp:150
[2023-08-16T19:28:15.155Z]       0x1f119338	DB::PipelineExec::fetchBlock(DB::Block&, unsigned long&) [gtests_dbms+521245496]
[2023-08-16T19:28:15.155Z]                 	dbms/src/Flash/Pipeline/Exec/PipelineExec.cpp:139
[2023-08-16T19:28:15.155Z]       0x1f118d1f	DB::PipelineExec::executeImpl() [gtests_dbms+521243935]
[2023-08-16T19:28:15.155Z]                 	dbms/src/Flash/Pipeline/Exec/PipelineExec.cpp:115
[2023-08-16T19:28:15.155Z]       0x1f118315	DB::PipelineExec::execute() [gtests_dbms+521241365]
[2023-08-16T19:28:15.155Z]                 	dbms/src/Flash/Pipeline/Exec/PipelineExec.cpp:97
[2023-08-16T19:28:15.155Z]        0x52955d7	DB::tests::SimpleOperatorTestRunner::executeAndAssert(std::__1::shared_ptr<tipb::DAGRequest> const&, std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&) [gtests_dbms+86595031]
[2023-08-16T19:28:15.155Z]                 	dbms/src/Flash/Pipeline/Exec/tests/gtest_simple_operator.cpp:124
[2023-08-16T19:28:15.155Z]        0x5283c39	DB::tests::SimpleOperatorTestRunner_Projection_Test::TestBody() [gtests_dbms+86522937]
[2023-08-16T19:28:15.155Z]                 	dbms/src/Flash/Pipeline/Exec/tests/gtest_simple_operator.cpp:192
[2023-08-16T19:28:15.155Z]       0x1a9fccf1	void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) [gtests_dbms+446680305]
[2023-08-16T19:28:15.155Z]                 	contrib/googletest/googletest/src/gtest.cc:2479
[2023-08-16T19:28:15.155Z]       0x1a99b499	testing::Test::Run() [gtests_dbms+446280857]
[2023-08-16T19:28:15.155Z]                 	contrib/googletest/googletest/src/gtest.cc:2517
[2023-08-16T19:28:15.155Z]       0x1a99e628	testing::TestInfo::Run() [gtests_dbms+446293544]
[2023-08-16T19:28:15.155Z]                 	contrib/googletest/googletest/src/gtest.cc:2693
[2023-08-16T19:28:15.155Z]       0x1a99fba0	testing::TestCase::Run() [gtests_dbms+446299040]
[2023-08-16T19:28:15.155Z]                 	contrib/googletest/googletest/src/gtest.cc:2811
[2023-08-16T19:28:15.155Z]       0x1a9ca5b9	testing::internal::UnitTestImpl::RunAllTests() [gtests_dbms+446473657]
[2023-08-16T19:28:15.155Z]                 	contrib/googletest/googletest/src/gtest.cc:5177
[2023-08-16T19:28:15.155Z]       0x1a9ff2f1	bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) [gtests_dbms+446690033]
[2023-08-16T19:28:15.155Z]                 	contrib/googletest/googletest/src/gtest.cc:2479
[2023-08-16T19:28:15.155Z]       0x1a9c8e32	testing::UnitTest::Run() [gtests_dbms+446467634]
[2023-08-16T19:28:15.155Z]                 	contrib/googletest/googletest/src/gtest.cc:4786
[2023-08-16T19:28:15.155Z]        0xc920a0b	main [gtests_dbms+210897419]
[2023-08-16T19:28:15.155Z]                 	dbms/src/TestUtils/gtests_dbms_main.cpp:117
[2023-08-16T19:28:15.155Z]   0x7ff8fd684555	__libc_start_main [libc.so.6+140629]
[2023-08-16T19:28:15.155Z]        0x48b09e9	<unknown symbol> [gtests_dbms+76220905]
```
```
==2214160==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60d000024b70 at pc 0x00001cb76f87 bp 0x7ffd1a183f50 sp 0x7ffd1a183f48
READ of size 8 at 0x60d000024b70 thread T0
    #0 0x1cb76f86 in std::__1::shared_ptr<MemoryTracker>::operator->() const /data3/huanghaisheng/tiflash-env/sysroot/bin/../include/c++/v1/__memory/shared_ptr.h:589:16
    #1 0x1cb76f86 in DB::AutoSpillTrigger::triggerAutoSpill() /data3/huanghaisheng/git-repo/tiflash/dbms/src/Core/AutoSpillTrigger.h:57:37
    #2 0x1cb76f86 in DB::PipelineExecutorContext::triggerAutoSpill() const /data3/huanghaisheng/git-repo/tiflash/dbms/src/Flash/Executor/PipelineExecutorContext.h:156:33
    #3 0x1cb76f86 in DB::TransformOp::tryOutput(DB::Block&) /data3/huanghaisheng/git-repo/tiflash/dbms/src/Operators/Operator.cpp:150:18
    #4 0x1f0be8e7 in DB::PipelineExec::fetchBlock(DB::Block&, unsigned long&) /data3/huanghaisheng/git-repo/tiflash/dbms/src/Flash/Pipeline/Exec/PipelineExec.cpp:139:35
    #5 0x1f0be2ce in DB::PipelineExec::executeImpl() /data3/huanghaisheng/git-repo/tiflash/dbms/src/Flash/Pipeline/Exec/PipelineExec.cpp:115:22
    #6 0x1f0bd8c4 in DB::PipelineExec::execute() /data3/huanghaisheng/git-repo/tiflash/dbms/src/Flash/Pipeline/Exec/PipelineExec.cpp:97:22
    #7 0x5259955 in DB::tests::SimpleOperatorTestRunner::executeAndAssert(std::__1::shared_ptr<tipb::DAGRequest> const&, std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&) /data3/huanghaisheng/git-repo/tiflash/dbms/src/Flash/Pipeline/Exec/tests/gtest_simple_operator.cpp:123:29
    #8 0x5245e2a in DB::tests::SimpleOperatorTestRunner_Projection_Test::TestBody() /data3/huanghaisheng/git-repo/tiflash/dbms/src/Flash/Pipeline/Exec/tests/gtest_simple_operator.cpp:186:9
    #9 0x1a9be1e0 in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /data3/huanghaisheng/git-repo/tiflash/contrib/googletest/googletest/src/gtest.cc:2443:10
    #10 0x1a9be1e0 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /data3/huanghaisheng/git-repo/tiflash/contrib/googletest/googletest/src/gtest.cc:2479:14
    #11 0x1a95c988 in testing::Test::Run() /data3/huanghaisheng/git-repo/tiflash/contrib/googletest/googletest/src/gtest.cc:2517:5
    #12 0x1a95fb17 in testing::TestInfo::Run() /data3/huanghaisheng/git-repo/tiflash/contrib/googletest/googletest/src/gtest.cc:2693:11
    #13 0x1a96108f in testing::TestCase::Run() /data3/huanghaisheng/git-repo/tiflash/contrib/googletest/googletest/src/gtest.cc:2811:28
    #14 0x1a98baa8 in testing::internal::UnitTestImpl::RunAllTests() /data3/huanghaisheng/git-repo/tiflash/contrib/googletest/googletest/src/gtest.cc:5177:43
    #15 0x1a9c07e0 in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /data3/huanghaisheng/git-repo/tiflash/contrib/googletest/googletest/src/gtest.cc:2443:10
    #16 0x1a9c07e0 in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /data3/huanghaisheng/git-repo/tiflash/contrib/googletest/googletest/src/gtest.cc:2479:14
    #17 0x1a98a321 in testing::UnitTest::Run() /data3/huanghaisheng/git-repo/tiflash/contrib/googletest/googletest/src/gtest.cc:4786:10
    #18 0xc8e238a in RUN_ALL_TESTS() /data3/huanghaisheng/git-repo/tiflash/contrib/googletest/googletest/include/gtest/gtest.h:2341:46
    #19 0xc8e238a in main /data3/huanghaisheng/git-repo/tiflash/dbms/src/TestUtils/gtests_dbms_main.cpp:117:16
    #20 0x7f5bac63feaf in __libc_start_call_main (/usr/lib64/libc.so.6+0x3feaf)
    #21 0x7f5bac63ff5f in __libc_start_main@GLIBC_2.2.5 (/usr/lib64/libc.so.6+0x3ff5f)
    #22 0x48778a4 in _start (/data3/huanghaisheng/git-repo/tiflash/cmake-asan/dbms/gtests_dbms+0x48778a4)

0x60d000024b70 is located 0 bytes to the right of 144-byte region [0x60d000024ae0,0x60d000024b70)
allocated by thread T0 here:
    #0 0x4925c9d in operator new(unsigned long) /root/llvm-project/compiler-rt/lib/asan/asan_new_delete.cpp:95:3
    #1 0x5245d99 in void* std::__1::__libcpp_operator_new<unsigned long>(unsigned long) /data3/huanghaisheng/tiflash-env/sysroot/bin/../include/c++/v1/new:235:10
    #2 0x5245d99 in std::__1::__libcpp_allocate(unsigned long, unsigned long) /data3/huanghaisheng/tiflash-env/sysroot/bin/../include/c++/v1/new:261:10
    #3 0x5245d99 in std::__1::allocator<DB::ColumnWithTypeAndName>::allocate(unsigned long) /data3/huanghaisheng/tiflash-env/sysroot/bin/../include/c++/v1/__memory/allocator.h:108:38
    #4 0x5245d99 in std::__1::allocator_traits<std::__1::allocator<DB::ColumnWithTypeAndName> >::allocate(std::__1::allocator<DB::ColumnWithTypeAndName>&, unsigned long) /data3/huanghaisheng/tiflash-env/sysroot/bin/../include/c++/v1/__memory/allocator_traits.h:262:20
    #5 0x5245d99 in std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> >::__vallocate(unsigned long) /data3/huanghaisheng/tiflash-env/sysroot/bin/../include/c++/v1/vector:1015:37
    #6 0x5245d99 in std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> >::vector(std::initializer_list<DB::ColumnWithTypeAndName>) /data3/huanghaisheng/tiflash-env/sysroot/bin/../include/c++/v1/vector:1356:9
    #7 0x5245d99 in DB::tests::SimpleOperatorTestRunner_Projection_Test::TestBody() /data3/huanghaisheng/git-repo/tiflash/dbms/src/Flash/Pipeline/Exec/tests/gtest_simple_operator.cpp:188:13
    #8 0x1a9be1e0 in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /data3/huanghaisheng/git-repo/tiflash/contrib/googletest/googletest/src/gtest.cc:2443:10
    #9 0x1a9be1e0 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /data3/huanghaisheng/git-repo/tiflash/contrib/googletest/googletest/src/gtest.cc:2479:14
    #10 0x1a95c988 in testing::Test::Run() /data3/huanghaisheng/git-repo/tiflash/contrib/googletest/googletest/src/gtest.cc:2517:5
    #11 0x1a95fb17 in testing::TestInfo::Run() /data3/huanghaisheng/git-repo/tiflash/contrib/googletest/googletest/src/gtest.cc:2693:11
    #12 0x1a96108f in testing::TestCase::Run() /data3/huanghaisheng/git-repo/tiflash/contrib/googletest/googletest/src/gtest.cc:2811:28
    #13 0x1a98baa8 in testing::internal::UnitTestImpl::RunAllTests() /data3/huanghaisheng/git-repo/tiflash/contrib/googletest/googletest/src/gtest.cc:5177:43
    #14 0x1a9c07e0 in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /data3/huanghaisheng/git-repo/tiflash/contrib/googletest/googletest/src/gtest.cc:2443:10
    #15 0x1a9c07e0 in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /data3/huanghaisheng/git-repo/tiflash/contrib/googletest/googletest/src/gtest.cc:2479:14
    #16 0x1a98a321 in testing::UnitTest::Run() /data3/huanghaisheng/git-repo/tiflash/contrib/googletest/googletest/src/gtest.cc:4786:10
    #17 0xc8e238a in RUN_ALL_TESTS() /data3/huanghaisheng/git-repo/tiflash/contrib/googletest/googletest/include/gtest/gtest.h:2341:46
    #18 0xc8e238a in main /data3/huanghaisheng/git-repo/tiflash/dbms/src/TestUtils/gtests_dbms_main.cpp:117:16
    #19 0x7f5bac63feaf in __libc_start_call_main (/usr/lib64/libc.so.6+0x3feaf)

SUMMARY: AddressSanitizer: heap-buffer-overflow /data3/huanghaisheng/tiflash-env/sysroot/bin/../include/c++/v1/__memory/shared_ptr.h:589:16 in std::__1::shared_ptr<MemoryTracker>::operator->() const
Shadow bytes around the buggy address:
  0x0c1a7fffc910: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c1a7fffc920: fa fa fa fa fa fa fa fa fd fd fd fd fd fd fd fd
  0x0c1a7fffc930: fd fd fd fd fd fd fd fd fd fd fa fa fa fa fa fa
  0x0c1a7fffc940: fa fa fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c1a7fffc950: fd fd fd fa fa fa fa fa fa fa fa fa 00 00 00 00
=>0x0c1a7fffc960: 00 00 00 00 00 00 00 00 00 00 00 00 00 00[fa]fa
  0x0c1a7fffc970: fa fa fa fa fa fa fd fd fd fd fd fd fd fd fd fd
  0x0c1a7fffc980: fd fd fd fd fd fd fd fa fa fa fa fa fa fa fa fa
  0x0c1a7fffc990: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c1a7fffc9a0: fd fa fa fa fa fa fa fa fa fa fd fd fd fd fd fd
  0x0c1a7fffc9b0: fd fd fd fd fd fd fd fd fd fd fd fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
```

**Comment by SeaRise** [comment]
has been fixed by https://github.com/pingcap/tiflash/pull/7917
